### ISSUE TITLE
Crawled CSV file format issue

### ISSUE THREAD

**Issue by yifeili98** [FHDA/PortalFetch#10]
The current csv file needs to be organized to a more structured format for DBImport to process
![image](https://user-images.githubusercontent.com/31260876/85640935-0408be00-b642-11ea-838d-6cff37e876d2.png)

**Comment by yifeili98** [comment]
The image below is a preferred format such that labs and corresponding classes are on different levels, and the garbled character should be removed.
![image](https://user-images.githubusercontent.com/31260876/85641115-80030600-b642-11ea-9fad-be47d1f0dd8c.png)

**Comment by hk-mp5a3** [comment]
Does the special character mean empty?

**Comment by yifeili98** [comment]
> Does the special character mean empty?

Yes, so it's not too hard to write something to organize the data

**Comment by emilylxf** [comment]
Thank you! I'll try to figure that out.
